***1. Data Loading***

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score, recall_score, precision_score
import math

# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/DataMining/Datasets/Selected_Features.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [3]:
dataset.groupby('class').count()

mfcc_m1  mfcc_m2  mfcc_m3  mfcc_m4  mfcc_m5  mfcc_m6  harmonics_m1  \
class                                                                          
Extreme       203      203      203      203      203      203           203   
Mild          212      212      212      212      212      212           212   
Minimal       112      112      112      112      112      112           112   
Moderate      144      144      144      144      144      144           144   

          harmonics_m2  harmonics_m4  harmonics_m5  ...  \
class                                               ...   
Extreme            203           203           203  ...   
Mild               212           212           212  ...   
Minimal            112           112           112  ...   
Moderate           144           144           144  ...   

          zero_crossing_rate_m1  zero_crossing_rate_m3  zero_crossing_rate_m4  \
class                                                                           
Extreme                     203                    203                    203   
Mild                        212                    212                    212   
Minimal                     112                    112                    112   
Moderate                    144                    144                    144   

          spectral_rollof_m1  spectral_rollof_m3  spectral_rollof_m4  \
class                                                                  
Extreme                  203                 203                 203   
Mild                     212                 212                 212   
Minimal                  112                 112                 112   
Moderate                 144                 144                 144   

          spectral_rollof_m6  spectral_flux_m2  spectral_flux_m3  \
class                                                              
Extreme                  203               203               203   
Mild                     212               212               212   
Minimal                  112               112               112   
Moderate                 144               144               144   

          spectral_flux_m4  
class                       
Extreme                203  
Mild                   212  
Minimal                112  
Moderate               144  

[4 rows x 26 columns]

In [4]:
y


array(['Mild', 'Moderate', 'Moderate', 'Extreme', 'Moderate', 'Moderate',
       'Moderate', 'Minimal', 'Moderate', 'Extreme', 'Extreme', 'Mild',
       'Mild', 'Mild', 'Extreme', 'Extreme', 'Mild', 'Extreme', 'Minimal',
       'Mild', 'Moderate', 'Minimal', 'Mild', 'Moderate', 'Mild',
       'Moderate', 'Extreme', 'Mild', 'Mild', 'Extreme', 'Moderate',
       'Extreme', 'Mild', 'Mild', 'Extreme', 'Mild', 'Extreme',
       'Moderate', 'Minimal', 'Extreme', 'Mild', 'Moderate', 'Mild',
       'Mild', 'Minimal', 'Extreme', 'Extreme', 'Minimal', 'Mild', 'Mild',
       'Minimal', 'Extreme', 'Moderate', 'Extreme', 'Extreme', 'Extreme',
       'Mild', 'Mild', 'Extreme', 'Minimal', 'Mild', 'Moderate', 'Mild',
       'Extreme', 'Moderate', 'Mild', 'Minimal', 'Extreme', 'Mild',
       'Mild', 'Mild', 'Extreme', 'Minimal', 'Mild', 'Mild', 'Mild',
       'Extreme', 'Extreme', 'Mild', 'Mild', 'Extreme', 'Minimal',
       'Minimal', 'Extreme', 'Extreme', 'Mild', 'Moderate', 'Moderate',
       'Extre

***Random Forest***

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# print(X_train)
# print(y_train)
# print(X_test)
# print(y_test)
test_pred = []
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# print(X_train)
# print(X_test)

# Training the Random Forest Classification model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)



# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
test_pred.append([y_test, y_pred])

acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=1, average='macro')
pres_score = precision_score(y_test, y_pred, pos_label=1, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)


# tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()


# sensitivity = tp/(tp+fn)
# specificity = tn/(tn+fp)


# # g_mean = math.sqrt(tp*tn)


# g_mean = math.sqrt(sensitivity*specificity)
print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)
# print("G-Mean - ", g_mean)

[[30  5  0  3]
 [ 6 19  8  7]
 [ 1 13  7  1]
 [15 16  2  2]]
Accuracy -  0.42962962962962964
Recall -  0.40994958988380037
Precision -  0.3752561256723298
F1 Score -  0.39183641120543655


***SVM***

In [6]:
# Splitting the dataset into the Training set and Test set

test_pred = []
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# print(X_train)
# print(y_train)
# print(X_test)
# print(y_test)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# print(X_train)
# print(X_test)

# Training the SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)



# Predicting the Test set results
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
test_pred.append([y_test, y_pred])
acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=1, average='macro')
pres_score = precision_score(y_test, y_pred, pos_label=1, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)


# tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()


# sensitivity = tp/(tp+fn)
# specificity = tn/(tn+fp)


# # g_mean = math.sqrt(tp*tn)


# g_mean = math.sqrt(sensitivity*specificity)
print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)
# print("G-Mean - ", g_mean)


[[23  9  1  5]
 [ 4 28  2  6]
 [ 0 14  8  0]
 [ 7 17  2  9]]
Accuracy -  0.5037037037037037
Recall -  0.48151059466848944
Precision -  0.5384049773755657
F1 Score -  0.5083709042877228


***Gaussian Naive Bayes***

In [7]:
test_pred = []
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# print(X_train)
# print(y_train)
# print(X_test)
# print(y_test)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# print(X_train)
# print(X_test)

# Training the Naive Bayes model on the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)



# Predicting the Test set results
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
test_pred.append([y_test, y_pred])

acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=1, average='macro')
pres_score = precision_score(y_test, y_pred, pos_label=1, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)


# tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()


# sensitivity = tp/(tp+fn)
# specificity = tn/(tn+fp)


# g_mean = math.sqrt(tp*tn)


# g_mean = math.sqrt(sensitivity*specificity)
print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)
# print("G-Mean - ", g_mean)


[[28  5  2  3]
 [ 4 11 20  5]
 [ 0  6 15  1]
 [10 11  8  6]]
Accuracy -  0.4444444444444444
Recall -  0.46627221462747775
Precision -  0.43333333333333335
F1 Score -  0.4491997486303679


***Logistic Regression***

In [8]:
test_pred = []
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
# print(X_train)
# print(y_train)
# print(X_test)
# print(y_test)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# print(X_train)
# print(X_test)

# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)


# Predicting the Test set results
y_pred = classifier.predict(X_test)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
test_pred.append([y_test, y_pred])
acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=1, average='macro')
pres_score = precision_score(y_test, y_pred, pos_label=1, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)


# tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()


# sensitivity = tp/(tp+fn)
# specificity = tn/(tn+fp)


# g_mean = math.sqrt(tp*tn)


# g_mean = math.sqrt(sensitivity*specificity)
print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)
# print("G-Mean - ", g_mean)

[[26  8  0  4]
 [ 5 26  6  3]
 [ 0 12 10  0]
 [ 9 13  5  8]]
Accuracy -  0.5185185185185185
Recall -  0.5043318523581681
Precision -  0.5250504439063761
F1 Score -  0.5144826444318981


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [9]:
len(X_train)

536

***AdaBoost***

In [13]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from sklearn.tree import DecisionTreeClassifier
# smote_on_1 = 212
# smote = SMOTE(sampling_strategy={'Minimal': smote_on_1,'Moderate': smote_on_1, 'Extreme': smote_on_1})
# X, y = smote.fit_resample(X, y)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
base_classifier = DecisionTreeClassifier(max_depth=10)
classifier= AdaBoostClassifier(base_estimator=base_classifier)  
classifier.fit(X_train, y_train)
y_pred= classifier.predict(X_test)

acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=0, average='macro') # binary?
pres_score = precision_score(y_test, y_pred, pos_label=0, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)
# g_mean = geometric_mean_score(y_test, y_pred)

print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)

Accuracy -  0.5333333333333333
Recall -  0.498491968557758
Precision -  0.5417694284881784
F1 Score -  0.5192304735682848


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 0) is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 0) is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


***XGBOOST***


In [ ]:
test_pred = []
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Training XGBoost on the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

test_pred.append([y_test, y_pred])
acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=1, average='macro')
pres_score = precision_score(y_test, y_pred, pos_label=1, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)




# tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()


# sensitivity = tp/(tp+fn)
# specificity = tn/(tn+fp)


# # g_mean = math.sqrt(tp*tn)


# g_mean = math.sqrt(sensitivity*specificity)
print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)
# print("G-Mean - ", g_mean)

***Bagging***

In [14]:
# smote_on_1 = 212
# smote = SMOTE(sampling_strategy={'Minimal': smote_on_1,'Moderate': smote_on_1, 'Extreme': smote_on_1})
# X, y = smote.fit_resample(X, y)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
base_classifier = DecisionTreeClassifier(max_depth=10)
classifier= BaggingClassifier(base_estimator=base_classifier)  
classifier.fit(X_train, y_train)
y_pred= classifier.predict(X_test)

acc_score = accuracy_score(y_test, y_pred)
rec_score = recall_score(y_test, y_pred, pos_label=0, average='macro') # binary?
pres_score = precision_score(y_test, y_pred, pos_label=0, average='macro')
f1_score = 2 * (pres_score * rec_score) / (pres_score + rec_score)
# g_mean = geometric_mean_score(y_test, y_pred)

print("Accuracy - ", acc_score)
print("Recall - ", rec_score)
print("Precision - ", pres_score)
print("F1 Score - ", f1_score)

Accuracy -  0.5185185185185185
Recall -  0.4950914217361586
Precision -  0.512474382963557
F1 Score -  0.5036329531655842


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 0) is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 0) is ignored when average != 'binary' (got 'macro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
